name: document_manager
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.2
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  

  # Icons
  cupertino_icons: ^1.0.6

  # Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  uuid: ^4.2.1

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  

  # Documents Specific
  file_picker: ^9.1.0
  image_picker: ^1.0.4
  path: ^1.8.3
  flutter_pdfview: ^1.3.2
  video_player: ^2.9.3
  chewie: ^1.10.0
  just_audio: ^0.9.36
  excel: ^2.1.0
  open_file: ^3.3.2
  google_fonts: ^6.1.0
  mime: ^1.0.4
  record: ^5.2.1
  permission_handler: ^11.4.0
  flutter_image_compress: ^2.4.0
  pdf_render: ^1.4.12
  synchronized: ^3.3.0+3
  get_thumbnail_video: ^0.7.3
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.3
 

 


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/
    

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app-logo.png"